siteTitle = "Rachel Muñoz"
siteDescr = "art || tech || art && tech"
siteAuthor = "Rachel Muñoz"


siteTwitterUrl = "https://twitter.com/rachelumunoz"
siteGithubUrl = "https://github.com/rachelumunoz"
siteEmailUrl = "rachelumunoz@gmail.com"


googleAnalyticsId = ""

linkPrefix = "/gatsby-starter-lumen"